apiVersion: enterpriseagentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayBackend
metadata:
  name: ent-petstore-openapi-backend
  namespace: agentgateway-system
spec:
  entMcp:
    targets:
    - name: ent-petstore-openapi
      static:
        host: petstore.agentgateway-system.svc.cluster.local
        port: 8080
        protocol: OpenAPI
        openAPI:
          schemaRef:
            name: petstore-openapi-schema
