apiVersion: enterpriseagentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayPolicy
metadata:
  annotations: {}
  name: combined-databricks-exchange
  namespace: agentgateway-system
spec:
  backend:
    tokenExchange:
      elicitation:
        secretName: combined-databricks-token-exchange
  targetRefs:
    - group: agentgateway.dev
      kind: AgentgatewayBackend
      name: combined-databricks-backend
