apiVersion: v1
data:
  access_token_url: REDACTED
  app_id: REDACTED
  authorize_url: REDACTED
  client_id: REDACTED
  client_secret: REDACTED
  mcp_resource: REDACTED
  scopes: REDACTED
kind: Secret
metadata:
  annotations: {}
  name: combined-databricks-token-exchange
  namespace: agentgateway-system
type: Opaque
