apiVersion: v1
data:
  app_id: REDACTED
  base_url: REDACTED
  mcp_resource: REDACTED
  scopes: REDACTED
kind: Secret
metadata:
  annotations: {}
  name: combined-gitlab-token-exchange
  namespace: agentgateway-system
type: Opaque
