apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  annotations: {}
  name: entra-jwks
  namespace: agentgateway-system
spec:
  policies:
    tls: {}
  static:
    host: login.microsoftonline.com
    port: 443
