apiVersion: enterpriseagentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayBackend
metadata:
  name: ent-gitlab-openapi-backend
  namespace: agentgateway-system
spec:
  policies:
    tls: {}
    mcp:
      authentication:
        audiences:
        - api://REDACTED
        issuer: https://sts.windows.net/REDACTED/
        jwks:
          backendRef:
            group: agentgateway.dev
            kind: AgentgatewayBackend
            name: entra-jwks
          cacheDuration: 5m
          jwksPath: REDACTED/discovery/v2.0/keys
        mode: Strict
        resourceMetadata:
          agentgateway.dev/issuer-proxy: http://enterprise-agentgateway.agentgateway-system.svc.cluster.local:7777/oauth-issuer
          authorizationServers:
          - https://mcp.servebeer.com/gitlab/openapi/mcp
          resource: https://mcp.servebeer.com/gitlab/openapi/mcp
          scopesSupported:
          - api://REDACTED/agentgateway
  entMcp:
    targets:
    - name: ent-gitlab-openapi
      static:
        host: gitlab.com
        port: 443
        path: /api/v4
        protocol: OpenAPI
        openAPI:
          schemaRef:
            name: gitlab-openapi-schema
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitlab-openapi-mcp
  namespace: agentgateway-system
spec:
  parentRefs:
  - name: agentgateway
  rules:
  - backendRefs:
    - group: enterpriseagentgateway.solo.io
      kind: EnterpriseAgentgatewayBackend
      name: ent-gitlab-openapi-backend
    matches:
    - path:
        type: PathPrefix
        value: /gitlab/openapi/mcp
    - path:
        type: PathPrefix
        value: /.well-known/oauth-protected-resource/gitlab/openapi/mcp
    - path:
        type: PathPrefix
        value: /.well-known/oauth-authorization-server/gitlab/openapi/mcp
---
apiVersion: enterpriseagentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayPolicy
metadata:
  name: gitlab-openapi-policy
  namespace: agentgateway-system
spec:
  backend:
    tls: {}
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: gitlab-openapi-mcp
  traffic:
    cors:
      allowCredentials: false
      allowHeaders:
      - '*'
      allowMethods:
      - '*'
      allowOrigins:
      - '*'
      maxAge: 5
---
apiVersion: enterpriseagentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayPolicy
metadata:
  name: ent-gitlab-openapi-exchange
  namespace: agentgateway-system
spec:
  backend:
    tokenExchange:
      elicitation:
        secretName: gitlab-token-exchange
  targetRefs:
  - group: enterpriseagentgateway.solo.io
    kind: EnterpriseAgentgatewayBackend
    name: ent-gitlab-openapi-backend
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-token-exchange
  namespace: agentgateway-system
type: Opaque
stringData:
  app_id: gitlab
  client_id: "REDACTED"
  client_secret: "REDACTED"
  authorize_url: "https://gitlab.com/oauth/authorize"
  access_token_url: "https://gitlab.com/oauth/token"
  scopes: "api"
  mcp_resource: "/gitlab/openapi/mcp"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-openapi-schema
  namespace: agentgateway-system
data:
  schema: |
    {"openapi":"3.0.3","info":{"title":"GitLab","description":"GitLab..."}, "...truncated..."}
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: entra-jwks
  namespace: agentgateway-system
spec:
  policies:
    tls: {}
  static:
    host: login.microsoftonline.com
    port: 443
