apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ${PG_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: "${PG_USER}"
            - name: POSTGRES_PASSWORD
              value: "${PG_PASSWORD}"
            - name: POSTGRES_DB
              value: "${PG_DB}"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ${PG_NAMESPACE}
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
